version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: aaf-mysql
    environment:
      MYSQL_DATABASE: aaf_db
      MYSQL_USER: aaf_user
      MYSQL_PASSWORD: aaf_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - aaf-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aaf-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aaf_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: aaf_user
      SPRING_DATASOURCE_PASSWORD: aaf_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 5
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 2000000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SERVER_PORT: 8080
    networks:
      - aaf-network

volumes:
  mysql_data:

networks:
  aaf-network:
