POST http://localhost:8080/api/posts/12/comments
Content-Type: application/json

{
  "content": "This is a reply to comment 456",
  "author": "ReplyUser",
  "profilePicture": "https://avatar.com/replyuser.png",
  "parentCommentId": 119
}

